fn main() {
    // Tauri 2.11.2+：remote 内容（主窗口导航到的 http://127.0.0.1:*/）默认无法调用应用命令，
    // 必须显式声明 AppManifest 命令清单，tauri-build 才会生成 allow-/deny- 权限文件
    // （写入 ./permissions/autogenerated/），再由 capabilities/main.json 引用。
    // 清单必须与 main.rs 的 generate_handler! 保持一致。
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "retry_start",
                "restart_service",
                "trigger_check_update",
                "open_update_dialog",
                "check_update",
                "start_update",
                "get_update_state",
                "get_pending_update",
                "dismiss_update",
                "show_notification",
                "set_window_busy",
                "show_main_window",
                "save_window_state",
                "read_dragged_file",
                "get_app_config",
                "set_notification_sound",
                "set_close_to_tray",
                "window_minimize",
                "window_maximize_toggle",
                "window_close",
                "window_toggle_fullscreen",
                "window_is_fullscreen",
            ]),
        ),
    )
    .expect("tauri-build 失败");
}
